server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: 0281
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

